/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { EnsRegistrar, EnsRegistrarInterface } from "../EnsRegistrar";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "node",
        type: "bytes32",
      },
    ],
    name: "resolver",
    outputs: [
      {
        name: "resolverAddress",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class EnsRegistrar__factory {
  static readonly abi = _abi;
  static createInterface(): EnsRegistrarInterface {
    return new utils.Interface(_abi) as EnsRegistrarInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EnsRegistrar {
    return new Contract(address, _abi, signerOrProvider) as EnsRegistrar;
  }
}
