name: Build/release

on:
    push:
        tags:
            - 'v*'
env:
    NUGG_APP_ETHERSCAN_KEY: ${{ secrets.NUGG_APP_ETHERSCAN_KEY }}
    NUGG_APP_INFURA_KEY: ${{ secrets.NUGG_APP_INFURA_KEY }}
    NUGG_APP_ALCHEMY_KEY: ${{ secrets.NUGG_APP_ALCHEMY_KEY }}
    NUGG_APP_GOOGLE_ANALYTICS_ID: ${{ secrets.NUGG_APP_GOOGLE_ANALYTICS_ID }}
    NODE_OPTIONS: '--experimental-modules'

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 18
            # for notarization:  https://samuelmeuli.com/blog/2019-12-28-notarizing-your-electron-app/
            # for signing: https://github.com/samuelmeuli/action-electron-builder
            # - name: Prepare for app notarization
            #   if: startsWith(matrix.os, 'macos')
            #   # Import Apple API key for app notarization on macOS
            #   run: |
            #       mkdir -p ~/private_keys/
            #       echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8
            - name: Build/release Electron app
              uses: samuelmeuli/action-electron-builder@v1
              with:
                  # GitHub token, automatically provided to the action
                  # (No need to define this secret in the repo settings)
                  github_token: ${{ secrets.github_token }}
                  mac_certs: ${{ secrets.mac_certs }}
                  mac_certs_password: ${{ secrets.mac_certs_password }}

                  # If the commit is tagged with a version (e.g. "v1.0.0"),
                  # release the app after building
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}
            #   env:
            #       API_KEY_ID: ${{ secrets.api_key_id }}
            #       API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}
