name: release

on:
    push:
        tags:
            - 'v*'
env:
    NUGG_APP_ETHERSCAN_KEY: ${{ secrets.NUGG_APP_ETHERSCAN_KEY }}
    NUGG_APP_INFURA_KEY: ${{ secrets.NUGG_APP_INFURA_KEY }}
    NUGG_APP_ALCHEMY_KEY: ${{ secrets.NUGG_APP_ALCHEMY_KEY }}
    NUGG_APP_GOOGLE_ANALYTICS_ID: ${{ secrets.NUGG_APP_GOOGLE_ANALYTICS_ID }}
    NUGG_APP_APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
    NUGG_APP_APPLE_ID_EMAIL: ${{ secrets.APPLE_ID_EMAIL }}
    NODE_OPTIONS: '--experimental-modules'
jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2
            - id: nvm
              name: read .nvmrc
              run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
            - uses: actions/setup-node@v2
              with:
                  node-version: '${{ steps.nvm.outputs.NVMRC }}'
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@nuggxyz'
            - run: yarn
            - run: yarn make
